SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS wisata;

create table wisata
(
    id           int auto_increment
        primary key,
    judul        varchar(255)                        not null,
    gambar       varchar(255)                        null,
    deskripsi    text                                null,
    jam_buka     varchar(10)                         null,
    jam_tutup    varchar(10)                         null,
    no_telepon   varchar(20)                         null,
    harga_tiket  decimal(10, 2)                      null,
    link_gmaps   text                                null,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    kategori     varchar(255)                        null,
    fasilitas    text                                null,
    galeri       text                                null,
    longitude    varchar(50)                         null,
    latitude     varchar(50)                         null,
    kode_wilayah varchar(50)                         null,
    alamat       varchar(255)                        null,
    event        text                                null
)
    collate = utf8mb4_unicode_ci;

INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (15, 'Kolam Renang Cangkring Sigaluh', 'utama/1765736002952-WhatsApp Image 2025-12-07 at 12.14.25.jpeg', 'Kolam Renang Cangkring Sigaluh', '07:30', '17:00', '6282243733333', 10000.00, 'https://maps.app.goo.gl/rJ9scm9B87QDzrfj9', '2025-12-14 18:13:25', '["Wisata Rekreasi"]', '["Toilet","Wahana Perosotan","Parkir Luas","Karaoke","Terapi Ikan","Kolam Air Panas"]', '["galeri/1765736004410-WhatsApp Image 2025-12-07 at 12.14.09.jpeg"]', ' 109.78754333886032', '-7.407615475474255', '33.04.07.2008', 'Jl. Ajibarang Secang, Gribig Wetan, Prigi, Kec. Sigaluh, Kab. Banjarnegara, Jawa Tengah', '');
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (16, 'Air Terjun Curug Pitu', 'utama/1765737520826-WhatsApp Image 2025-12-14 at 21.28.42.jpeg', 'Wisata alam Curug Pitu merupakan air terjun unik yang terdiri dari tujuh tingkatan, di mana kata “pitu” sendiri berarti tujuh dalam bahasa Jawa, dan tingkatan ketujuh menjadi yang paling sering dikunjungi karena keindahannya. Jarak antar curug berkisar antara 20–50 meter dengan jalur trekking yang cukup menguras tenaga, karena untuk mencapai tingkatan atas kamu harus melewati rute yang terus menanjak dan semakin menantang. Curug ketujuh memiliki ketinggian sekitar 30 meter dengan bentuk berundak seperti anak tangga, yang saat debit air sedang deras akan tampak bergelombang dan sangat memukau. Tebing batu hitam berpadu serasi dengan aliran air yang putih bersih serta tanaman hijau yang tumbuh subur di sekitarnya, menciptakan suasana alami yang menenangkan. Di bawahnya terdapat kolam alami yang relatif dangkal dan sering dimanfaatkan pengunjung untuk bermain air. Namun perlu diperhatikan, debit air Curug Pitu sangat bergantung pada musim, di mana saat musim hujan alirannya lebih deras, sementara di musim kemarau cenderung berkurang. Selain menikmati keindahannya, Curug Pitu juga kerap dijadikan lokasi aktivitas rappelling, baik untuk pemula maupun yang sudah berpengalaman, dengan catatan pengunjung perlu membawa peralatan sendiri.

referensi : https://www.idntimes.com/travel/destination/curug-pitu-banjarnegara-lokasi-rute-harga-dan-tips-wisata-01-gcvvx-tbm826', '08:00', '16:00', '628563188406', 5000.00, 'https://maps.app.goo.gl/zX6XgMVSqZJnSG4s8', '2025-12-14 18:38:42', '["Curug/Air Terjun","Wisata Alam"]', '["Rapeling","Toilet","Parkir"]', '[]', '109.75748789309816', '-7.4144577362198865', '33.04.07.2010', 'HQP5+424, Kemiri, Sigaluh, Kemiri, Banjaranegara, Kab. Banjarnegara, Jawa Tengah 53481', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (17, 'Seakong Agro Eduwisata', 'utama/1767616446493-MricaCategory.jpeg', 'Wisata Seakong Agro Eduwisata merupakan tempat wisata rekreasi sekaligus wisata edukasi yang berada di tepian Bendungan Jenderal Soedirman atau yang lebih dikenal sebagai Waduk Mrica. yang terletak di Kecamatan Wanadadi, Kabupaten Banjarnegara, tepatnya di sisi utara waduk. Akses jalan menuju Wisata Seakong sangat mudah dilalui menggunakan kendaraan roda dua maupun roda empat. Wisata ini menyajikan pemandangan indah Waduk Mrica dengan latar pegunungan di sisi selatan, serta aktivitas nelayan yang memancing atau menjala ikan yang menambah daya tarik tersendiri. Wisata Seakong tidak dipungut biaya masuk. Pengunjung hanya perlu membayar parkir sebesar Rp5.000 untuk kendaraan roda empat dan Rp2.000 untuk kendaraan roda dua. Di lokasi ini tersedia berbagai wahana seperti ATV, mini trail, trampolin, mini mining, odong-odong, perahu wisata, panahan, dan berkuda dengan tarif sekitar Rp10.000 per wahana. Selain itu, tersedia pula beragam jajanan dengan harga terjangkau seperti tempe mendoan, mi ayam, sosis bakar, dan jajanan lainnya, sehingga Wisata Seakong cocok untuk wisata keluarga dan tetap ramah di kantong.', '07:00', '23:00', '6281328404123', 0.00, 'https://maps.app.goo.gl/vmF8YsCQJ65PwgN76', '2025-12-14 19:00:34', '["Wisata Rekreasi","Waduk","Wisata Edukasi"]', '["ATV","Mini Trail","Parkir","Toilet","Trampolin","Mini Minning","Odong-odong","Perahu","Panahan","Berkuda","Warung"]', '["galeri/1767618566904-IMG20251220101546.jpg","galeri/1770864533274-photo_79_2026-01-28_20-11-19.jpg"]', '109.61975103899958', '-7.372301071129265', '33.04.10.2004', 'Dusun Dua, Wanadadi, Kec. Wanadadi, Kab. Banjarnegara, Jawa Tengah', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (19, 'Telaga Dringo', 'utama/1765740437650-Telaga Dringo.jpg', 'Telaga Dringo merupakan sebuah wisata alam yang berada di ketinggian 2.222 MDPL dan dikenal sebagai telaga tertinggi di Jawa Tengah. Telaga ini terletak di Desa Pekasiran, Kecamatan Batur, Kabupaten Banjarnegara, di sebelah barat daya Dataran Tinggi Dieng, serta berdekatan dengan objek wisata Sumur Jalatunda dan Kawah Candradimuka yang terkenal dengan cerita dan mitosnya. Suasana Telaga Dringo sangat asri, tenang, dan bebas polusi, dengan pemandangan perbukitan hijau yang mengelilingi telaga sehingga memberikan kesejukan udara dan keindahan alam yang menenangkan. Telaga Dringo terbentuk akibat letusan Gunung Sinila pada tahun 1786 yang menyisakan kawah mati dan kemudian terisi air hujan serta mata air di sekitarnya, sementara nama “Dringo” berasal dari tumbuhan yang banyak tumbuh di sekitar telaga. Pengunjung dapat mengeksplorasi keindahan Telaga Dringo dengan berkemah di tepi telaga dan menikmati pemandangan Dataran Tinggi Dieng, termasuk momen sunrise yang bisa terlihat lebih jelas dari Bukit Cemeti di dekat telaga. Akses menuju Telaga Dringo tergolong menantang karena harus melewati jalan aspal sempit di tengah hutan, sehingga disarankan menggunakan kendaraan sewaan dengan sopir berpengalaman atau ojek untuk mencapai lokasi.', '00:00', '00:00', '6281331794109', 6000.00, 'https://maps.app.goo.gl/MjmPd2iVR4m6h1SG9', '2025-12-14 19:27:19', '["Dieng","Wisata Alam"]', '["Camp Area","Parkir","Toilet","Warung","Sewa Alat Camping","Mushola"]', '[]', '109.84752030782059', '-7.1853040458895565', '33.04.16.2004', 'Sidomulyo, Pekasiran, Kec. Batur, Kab. Banjarnegara, Jawa Tengah', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (20, 'Desa Wisata Pagak', 'utama/1765741016547-pagaj.jpeg', 'Desa Wisata Pagak', '08:00', '17:00', '6285879580895', 5000.00, 'https://maps.app.goo.gl/mB3a5iYUNmZ3bDqW7', '2025-12-14 19:36:57', '["Desa Wisata"]', '["Toilet","Gazebo","Parkir","Kolam Renang"]', '[]', '109.46130626931267', '-7.4736731331636035', '33.04.02.2002', 'Jl. Banjar Dawa, Dusun Banjar Anyar, Pagak, Kec. Purwareja Klampok, Kab. Banjarnegara, Jawa Tengah', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (21, 'Kolam Renang Kalionggok', 'utama/1765742883493-kalionggok.jpg', 'Sebagai wisata rekreasi bernuansa edukatif, Wisata Kali Onggok merupakan destinasi yang cukup populer di kalangan masyarakat Banjarnegara, khususnya di Kecamatan Rakit dan sekitarnya, yang berlokasi di Desa Blabar Lor, Adipasir, Rakit, Banjarnegara, Jawa Tengah. Kali Onggok menghadirkan beragam fasilitas dalam satu kawasan, mulai dari kolam pemancingan yang dilengkapi pemandu wisata, di mana hasil pancing dapat langsung diolah di tempat atau dibawa pulang, hingga kolam utama dengan fasilitas snorkeling yang airnya jernih dan dihiasi replika gunung, jembatan, serta susunan batu di dasar kolam. Selain itu, tersedia kolam renang dengan kedalaman bertahap yang aman untuk balita, anak-anak, hingga remaja dan dipercantik dengan lukisan 3D, serta ruang meeting yang dapat dimanfaatkan untuk berbagai acara seperti reuni, pernikahan, dan seminar. Sebagai pelengkap, Coffee Joke’s hadir sebagai kafe dan resto yang menyajikan aneka makanan dan minuman berkualitas dengan harga terjangkau, berbagai olahan ikan, paket barbeque, serta live music harian yang membuat suasana berwisata di Kali Onggok semakin nyaman dan menyenangkan.', '08:00', '17:00', '6285227353340', 5000.00, 'https://maps.app.goo.gl/2tuAHdFqy7BY2Kkv8', '2025-12-14 20:08:06', '["Wisata Rekreasi","Wisata Edukasi"]', '["Toilet","Parkir"]', '[]', '109.5424019219349', '-7.423012814203003', '33.04.11.2005', 'Blabar Lor, Adipasir, Kec. Rakit, Kab. Banjarnegara, Jawa Tengah', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (22, 'Eduwisata Kampung Gagot', 'utama/1765743293075-Kampung-Gagot-1-1.jpg', 'Eduwisata Kampung Gagot', '08:00', '20:00', '-', 5000.00, 'https://maps.app.goo.gl/oZhkz9ZHpTRZQGQs7', '2025-12-14 20:14:54', '["Wisata Edukasi","Desa Wisata"]', '[]', '[]', '109.60432901269226', '-7.432082128336472', '33.04.04.2013', 'Puntukendil, Kutawuluh, Kec. Purwanegara, Kab. Banjarnegara, Jawa Tengah 53472', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (23, 'Kalianget Mangunan', 'utama/1765744405831-kalianget.jpg', 'Kalianget Mangunan', '08:00', '18:00', '6282137888959', 10000.00, 'https://maps.app.goo.gl/mANSMMafnoFnxWAL7', '2025-12-14 20:33:27', '["Wisata Alam"]', '["Gazebo","Caffe","Parkir","Toilet"]', '[]', '109.64002455715008', '-7.2336497645090345', ' 33.04.18.2001', 'Jl. Kalibening - Gripit, Jogjogan, Kalibening, Kec. Kalibening, Kab. Banjarnegara, Jawa Tengah 53458', null);
INSERT INTO wisata (id, judul, gambar, deskripsi, jam_buka, jam_tutup, no_telepon, harga_tiket, link_gmaps, created_at, kategori, fasilitas, galeri, longitude, latitude, kode_wilayah, alamat, event) VALUES (26, 'Seakong Agro Eduwisata', 'utama/1770869296176-photo_71_2026-01-28_20-11-19.jpg', 'Destinasi wisata seakong adalah wisata rekreasi yang cocok untuk bersantai bareng keluarga', '07:00', '20:00', '081328404123 ', 0.00, 'https://maps.app.goo.gl/vmF8YsCQJ65PwgN76', '2026-02-12 04:08:19', '["Wisata Rekreasi"]', '["Toilet","Parkir"]', '["galeri/1770869297704-photo_76_2026-01-28_20-11-19.jpg","galeri/1770869299176-photo_76_2026-01-28_20-11-19.jpg"]', '109.61975103899958', '-7.372301071129265', '33.04.10.2004', 'Dusun Dua, Wanadadi, Kec. Wanadadi, Kab. Banjarnegara, Jawa Tengah', null);

SET FOREIGN_KEY_CHECKS=1;
